/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CardCardInfo {
  /**
   * Номер карты с маской
   */
  cardNumber?: string;
  /**
   * Номер карты
   */
  fullCardNumber?: string;
  /**
   * Полное название карты
   */
  product?: string;
  /**
   * Название карты
   */
  type?: string;
  /**
   * Тип карты
   */
  cardType?: CardType;
  /**
   * Платежная система
   */
  paymentSystemType?: PaymentSystemType;
  /**
   * Дата окончания действия карты
   */
  expireDate?: string;
  isBlocked?: boolean;
  isDefaultAccount?: boolean;
  cvv?: string;
}

export enum CardType {
  Debit = "debit",
  Credit = "credit",
}

export enum PaymentSystemType {
  Visa = "visa",
  Mastercard = "mastercard",
  Unionpay = "unionpay",
  Unknown = "unknown",
}
