/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateTransferResponseIpsDetails } from "./createTransferResponseIpsDetails";

/**
 * Сформированный перевод (неподтвержденный)
 */
export interface CreateTransferResponse {
  /**
   * Id операции
   */
  id?: string;
  /**
   * Сумма перевода
   */
  amount?: number;
  /**
   * Тип валюты
   */
  currency?: string;
  comment?: string;
  /**
   * номер счета списания
   */
  from?: string;
  /**
   * PAN карты/номер счета зачисления
   */
  to?: string;
  // TODO: должно добавиться с бэка
  commission?: number;
  ipsDetails?: CreateTransferResponseIpsDetails;
}
