/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateTransferRequestIpsDetails } from "./createTransferRequestIpsDetails";

/**
 * Перевод
 */
export interface CreateTransferRequest {
  /**
   * ID карты/счета списания
   */
  fromProductId: number;
  /**
   * Сумма перевода
   */
  amount: number;
  /**
   * Тип валюты
   */
  currency: string;
  comment: string;
  /**
   * Тип счета зачисления: на счет клиенту ВТБ, между своими счетами, на кредитную карту, на дебетовую карту
   */
  transferType: CreateTransferRequest.TransferTypeEnum;
  /**
   * PAN карты/номер счета зачисления
   */
  to: string;
  ipsDetails?: CreateTransferRequestIpsDetails;
}
export namespace CreateTransferRequest {
  export type TransferTypeEnum = "IBAN" | "PAN" | "ALIAS" | "SELF";
  export const TransferTypeEnum = {
    IBAN: "IBAN" as TransferTypeEnum,
    PAN: "PAN" as TransferTypeEnum,
    ALIAS: "ALIAS" as TransferTypeEnum,
    SELF: "SELF" as TransferTypeEnum,
  };
}
