/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DepositDetailsDepositDetailAmount } from "./depositDetailsDepositDetailAmount";

export interface DepositDetailsDepositDetail {
  /**
   * Процентная ставка
   */
  rate?: string;
  /**
   * Перодичность выплаты/капитализации процентов
   */
  revenuePayment?: string;
  /**
   * Дополнительные участники
   */
  participant?: string;
  /**
   * Признак капитализации
   */
  isCapitalized?: boolean;
  /**
   * Дата начала
   */
  startDate?: string;
  /**
   * Дата окончания
   */
  endDate?: string;
  amount?: DepositDetailsDepositDetailAmount;
}
