/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LoanListDetailLoanInfo } from "./loanListDetailLoanInfo";
import { LoanListDetailPayment } from "./loanListDetailPayment";

/**
 * Информация о кредите клиента
 */
export interface LoanListDetail {
  /**
   * ID кредита
   */
  id: number;
  /**
   * Номер кредита
   */
  loanContractNumber: string;
  loanInfo: LoanListDetailLoanInfo;
  payment: LoanListDetailPayment;
}
