/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LoanDetailDebt } from "./loanDetailDebt";
import { LoanDetailLoanInfo } from "./loanDetailLoanInfo";
import { LoanDetailPayment } from "./loanDetailPayment";

/**
 * Подробная информация о кредите клиента
 */
export interface LoanDetail {
  /**
   * ID кредита
   */
  id: number;
  /**
   * Номер кредита
   */
  loanContractNumber?: string;
  loanInfo?: LoanDetailLoanInfo;
  debt?: LoanDetailDebt;
  payment?: LoanDetailPayment;
}
