/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Перевод
 */
export interface ReceiptRequest {
  /**
   * Сумма перевода
   */
  amount?: number;
  /**
   * Сумма комиссии
   */
  commission?: number;
  /**
   * Валюта платежа
   */
  currency?: string;
  /**
   * Дата и время
   */
  dateTime?: string;
  /**
   * Тип операции
   */
  operationType?: OperationType;
  /**
   * Отправитель
   */
  sender?: string;
  /**
   * Получатель
   */
  receiver?: string;
  /**
   * Назначение платежа
   */
  purpose?: string;
}

export enum OperationType {
  Card = "card",
  Account = "account",
  Payment = "payment",
}
