/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransferOperation } from "./transferOperation";

/**
 * Результат перевода
 */
export interface TransferConfirmationResponse {
  /**
   * Id операции в АБС
   */
  operationId?: number;
  operation?: TransferOperation;
  /**
   * Id операции
   */
  transferId?: string;
  /**
   * Время проведения операции
   */
  createdAt?: string;
}
