/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Перевод
 */
export interface TransferRequest {
  /**
   * ID карты/счета списания
   */
  fromId: number;
  /**
   * Тип счета списания: кредитная карта/дебетовая карта/счет
   */
  fromType: TransferFrom;
  /**
   * PAN карты/номер счета зачисления
   */
  to: string;
  /**
   * Тип счета зачисления: на счет клиенту ВТБ, между своими счетами, на кредитную карту, на дебетовую карту
   */
  toType: TransferTo;
  /**
   * Сумма перевода
   */
  amount: number;
  /**
   * Тип валюты
   */
  currency?: string;
  purpose?: string;
}

export enum TransferFrom {
  CREDITCARD = "CREDIT_CARD",
  DEBITCARD = "DEBIT_CARD",
  ACCOUNT = "ACCOUNT",
}

export enum TransferTo {
  SELFCARD = "SELF_CARD",
  SELFACCOUNT = "SELF_ACCOUNT",
  CARD = "CARD",
  ACCOUNT = "ACCOUNT",
}
