/**
 * Telegram adapter vtb - HTTP API
 * API vtb-bot-telegram-adapter
 *
 * OpenAPI spec version: 1.0
 * Contact: support@seven.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Детали операции
 */
export interface TransferOperation {
  /**
   * Счет списания или PAN карты
   */
  from?: string;
  /**
   * Счет зачисления или PAN карты
   */
  to?: string;
  /**
   * Тип операции
   */
  type?: TransferOperation.TypeEnum;
  /**
   * Сумма операции
   */
  amount?: number;
  /**
   * Сумма комиссии
   */
  commission?: number;
  /**
   * Общая сумма операции?
   */
  total?: number;
  /**
   * Валюта операции
   */
  currency?: string;
}
export namespace TransferOperation {
  export type TypeEnum = "A2A" | "A2C" | "C2C" | "C2A";
  export const TypeEnum = {
    A2A: "A2A" as TypeEnum,
    A2C: "A2C" as TypeEnum,
    C2C: "C2C" as TypeEnum,
    C2A: "C2A" as TypeEnum,
  };
}
