export enum OtpCheckErrorCode {
  CLIENT_ERROR = "CLIENT_ERROR",
  OTP_NOT_EQUAL = "OTP_NOT_EQUAL",
  OTP_EXPIRED = "OTP_EXPIRED",
  ARGUMENT_NOT_VALID = "ARGUMENT_NOT_VALID",
  OTP_LIMIT_EXCESS = "OTP_LIMIT_EXCESS",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
