name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build and push Docker image
        run: |
          docker build -t wishlist-ui .
          docker tag wishlist-ui:latest ${{ secrets.DOCKER_REPO_URL }}/wishlist-ui:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_REPO_URL }}/wishlist-ui:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_REPO_URL }}/wishlist-ui:latest
            sudo docker stop wishlist-ui-app || true
            sudo docker rm wishlist-ui-app || true
            sudo docker run -d -p 80:80 --name wishlist-ui-app ${{ secrets.DOCKER_REPO_URL }}/wishlist-ui:latest